[package]
name = "cybele-cli"
version = "0.1.0"
edition = "2021"
authors = ["Bastien Teinturier"]
license = "MIT"
repository = "https://github.com/cybele-labs/cybele-cli"
description = "Command-line interface for the cybele password manager."

[dependencies]
rand = "0.8.5"
rpassword = "7.3.1"
rprompt = "2.1.1"
cybele-core = { git = "https://github.com/cybele-labs/cybele-core" }